steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/modified-glyph-378521/aws-ecs-test:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/modified-glyph-378521/aws-ecs-test:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aws-ecs-test'
      - '--image'
      - 'gcr.io/modified-glyph-378521/aws-ecs-test:$COMMIT_SHA'
      - '--region'
      - ' us-central1'
images:
  - 'gcr.io/modified-glyph-378521/aws-ecs-test:$COMMIT_SHA'